// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQvwOWnzcIsojA5tox2yJ3xhl2DkG7eo',
    appId: '1:478832334301:web:77ca5006d9fda9985d5234',
    messagingSenderId: '478832334301',
    projectId: 'the-owl-493408',
    authDomain: 'the-owl-493408.firebaseapp.com',
    storageBucket: 'the-owl-493408.firebasestorage.app',
    measurementId: 'G-LC6SJRW0P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHIAwOP8TA4nITorA2gMnmuUPUdlGOlgU',
    appId: '1:478832334301:android:259b5a87bfb3732c5d5234',
    messagingSenderId: '478832334301',
    projectId: 'the-owl-493408',
    storageBucket: 'the-owl-493408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYdcXzM5yrbHRBi2la7H2PfI0AHxYyyuQ',
    appId: '1:478832334301:ios:6b263cb871521d105d5234',
    messagingSenderId: '478832334301',
    projectId: 'the-owl-493408',
    storageBucket: 'the-owl-493408.firebasestorage.app',
    iosBundleId: 'com.example.owlapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYdcXzM5yrbHRBi2la7H2PfI0AHxYyyuQ',
    appId: '1:478832334301:ios:43f5901541f3fdd05d5234',
    messagingSenderId: '478832334301',
    projectId: 'the-owl-493408',
    storageBucket: 'the-owl-493408.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQvwOWnzcIsojA5tox2yJ3xhl2DkG7eo',
    appId: '1:478832334301:web:e08383612913007c5d5234',
    messagingSenderId: '478832334301',
    projectId: 'the-owl-493408',
    authDomain: 'the-owl-493408.firebaseapp.com',
    storageBucket: 'the-owl-493408.firebasestorage.app',
    measurementId: 'G-S61EKH76VX',
  );
}
